name: 🔍 PR Validation

on:
  pull_request:
    branches: [main, develop]
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - 'angular.json'
      - 'tsconfig.json'
      - 'karma.conf.js'
      - 'biome.json'
  push:
    branches: [main, develop]
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - 'angular.json'
      - 'tsconfig.json'
      - 'karma.conf.js'
      - 'biome.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality-checks:
    name: 🧪 Quality Checks
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: 🔧 Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: 🎯 Biome Check (Lint + Format)
        run: npm run check
        continue-on-error: false

      - name: 🔍 TypeScript Check
        run: npx tsc --noEmit --skipLibCheck
        continue-on-error: false

      - name: 🧪 Run Tests with Coverage
        run: npm run test:ci
        continue-on-error: false

      - name: 📊 Upload Coverage Reports
        uses: codecov/codecov-action@v3
        if: always()
        with:
          file: ./coverage/bobapp/lcov.info
          flags: frontend
          name: frontend-coverage
          fail_ci_if_error: false

      - name: 📈 Coverage Comment
        uses: romeovs/lcov-reporter-action@v0.3.1
        if: github.event_name == 'pull_request'
        with:
          lcov-file: ./coverage/bobapp/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
          title: 📊 Frontend Coverage Report

  build-check:
    name: 🏗️ Build Check
    runs-on: ubuntu-latest
    needs: quality-checks
    timeout-minutes: 10
    
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: 🔧 Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: 🏗️ Build Production
        run: npm run build:prod
        continue-on-error: false

      - name: 📦 Upload Build Artifacts
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: build-artifacts
          path: dist/
          retention-days: 1

  pr-status:
    name: ✅ PR Status
    runs-on: ubuntu-latest
    needs: [quality-checks, build-check]
    if: always()
    
    steps:
      - name: 🎉 All Checks Passed
        if: needs.quality-checks.result == 'success' && needs.build-check.result == 'success'
        run: |
          echo "✅ All quality checks passed!"
          echo "🚀 PR is ready to be merged"

      - name: ❌ Some Checks Failed
        if: needs.quality-checks.result != 'success' || needs.build-check.result != 'success'
        run: |
          echo "❌ Some quality checks failed!"
          echo "🔧 Please fix the issues before merging"
          exit 1 